"""Create assemblies and assembly_items tables

Revision ID: ba7989951903
Revises: 0fc5631a487a
Create Date: 2026-07-20 11:30:13.314690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7989951903'
down_revision = '0fc5631a487a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_markup_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('assembly_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('cost_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('waste_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assembly_items')
    op.drop_table('assemblies')
    # ### end Alembic commands ###
