"""Create estimate sections and line items

Revision ID: f57338a61491
Revises: dbb1dcdeac3a
Create Date: 2026-07-20 11:54:44.913236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57338a61491'
down_revision = 'dbb1dcdeac3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_version_id'], ['estimate_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_section_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=50), nullable=False),
    sa.Column('cost_item_id', sa.Integer(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('waste_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('markup_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('extended_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ),
    sa.ForeignKeyConstraint(['estimate_section_id'], ['estimate_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate_line_items')
    op.drop_table('estimate_sections')
    # ### end Alembic commands ###
